---
title: "Exploring the Role of Self-Compassion in Promoting Resilience and Well-Being Among Rescue Workers"

keywords: "self-compassion; rescue workers; nomological network; psychometrics; scales; factor analysis"

latex_engine: "xelatex"

bibliography: [bibliography.bib]
csl: "apa-with-abstract.csl"
---

# Introduction

The challenges faced by rescue workers (RWs) and healthcare workers (HCWs) involve consistently confronting the distress of others. Despite their proactive efforts to alleviate suffering, the demands of compassion can sometimes exceed its restorative effects, resulting in "compassion fatigue" [@joinson1992coping], burn-out [ref], and post-traumatic stress [ref]. Therefore, it is crucial to comprehend and promote the internal and external factors that support the resilience of these workers [@mao2022concept].

In recent years, the concept of "self" has gained interest as a vital construct for understanding individual differences in coping with stress [@beck2016self]. Self-compassion, representing specific ways of relating to oneself, has been found to have a positive impact on mental health [@macbeth2012exploring]. Additionally, a compassionate mindset towards oneself has been proposed as a protective factor against psychopathology, such as Post-Traumatic Stress Disorder (PTSD)[@wilson2019effectiveness; @wong2017self].
The present research focuses on the role of self-compassion as a coping mechanism among RWs. 

Specifically, the study aims to:

- Investigate whether there is a credible difference in self-compassion between RWs and a control community sample.
- Explore individual differences in the ability of RWs to rely on self-compassion and investigate how these differences relate to latent profiles of personality dimensions, and protective and risk factors for compassion fatigue and burn-out.
- Examine the relationship between direct vs indirect involvement in alleviating the suffering of others (job qualifications) and the ability to rely on self-compassion.

By addressing these research questions, the study aims to shed light on the role of self-compassion in RWs, its potential impact on their mental health and well-being, and its implications for promoting resilience and reducing the risk of negative outcomes such as compassion fatigue and burn-out.


## Personality traits and coping strategies as protective factors

Personality traits play a crucial role in determining an individual's susceptibility to burnout. For instance, a meta-analysis conducted by @swider2010born revealed that the Five Factor Model of Personality, comprising neuroticism, extraversion, agreeableness, conscientiousness, and openness, collectively account for a significant proportion of the variance in levels of job burnout among individuals. This finding suggests that personality traits are a potent predictor of burnout levels, implying that the etiology of burnout may not solely originate from external factors but also from intrinsic personality attributes. Specifically, @bianchi2018burnout found that neuroticism is the strongest correlate for burnout. Individuals with low levels of extraversion tend to focus on negative aspects of events and use predominantly emotion-focused coping strategies [@connor2007relations]. Moreover, individuals with low levels of conscientiousness tend to experience higher levels of depersonalization and reduced personal accomplishment [@kokkinos2007job]. Conversely, individuals with high levels of agreeableness exhibit a greater ability to build successful interpersonal relationships at work, are gentle, and cooperative, and show lower levels of burnout [@angelini2023big]. On the other hand, the literature has not established a clear link between openness and burnout [@angelini2023big; @ruaducu2022personality]. Therefore, we may expect that elevated levels of neuroticism and lower levels of extraversion, agreeableness, and conscientiousness (but not openness) may provide a "personality marker" for rescue workers who are less able to mobilize internal resources and build resistance against stressors.

Coping refers to the cognitive and behavioral efforts individuals make to manage environmental stressors, as described by @lazarus1984stress. Research has identified two types of coping strategies: adaptive (problem-solving and cognitive reappraisal) and maladaptive (suppression, rumination, and avoidance). Studies have consistently found that maladaptive coping strategies are particularly harmful to psychological well-being, as evidenced by @joormann2016examining, @liu2017selection, and @moritz2016more. In contrast, the lack of adaptive coping strategies seems to be less relevant to the development of psychological disorders, as suggested by studies conducted by @aldao2012adaptive and @moritz2016more.

A considerable amount of research has also demonstrated a clear relationship between personality traits and coping strategies [@sica2021facing]. However, @connor2007relations meta-analysis comprising 124 studies emphasized the importance of distinguishing between specific strategies. Specifically, extraversion showed positive correlations with problem-focused and emotion-focused strategies. On the other hand, neuroticism was negatively related to problem-focused and positive-oriented strategies, particularly acceptance, and positively related to emotional-focused and avoidance-oriented strategies. Agreeableness and openness exhibited a weak association with coping, primarily with social support and problem-focused strategies, while conscientiousness showed a strong link to problem-focused strategies. Additionally, the use of drugs and alcohol, classified as avoidance-oriented strategies, was negatively associated with Agreeableness and Conscientiousness [@afshar2015diagnostic; @connor2007relations].

Furthermore, it has been established that having access to sufficient internal and external resources can help individuals cope with situational demands, as well as build resistance against stressors. For RWs, perceived social support is a crucial external resource that plays a significant role in mitigating burnout. Studies conducted by @setti2016role have shown that RWs who perceive support from their colleagues and superiors are less likely to experience emotional exhaustion, depersonalization, and inefficacy, which are the three dimensions of burnout. These findings are consistent with previous research that has linked social support to lower levels of burnout and posttraumatic symptoms [@armstrong2004influence]. The stress-buffering hypothesis [@cohen1985stress], the social support deterioration model [@norris1996received], and the conservation of resources model [@hobfoll1989conservation] all suggest that perceived social support can protect against the negative effects of stress.

The overall psychological distressing symptoms in RWs often linked to burnout and PTSD. The meta-analysis of @berger2012rescuers, for example, shows that RWs  have a prevalence of PTSD that is much higher than that of the general population. Therefore, the identification of individual differences that signal increased risk for PTSD is important.

In summary, according to the above-discussed literature, we can posit that high levels of neuroticis and low levels of extraversion, agreeableness, and conscientiousness (regardless of openness), high levels of maladaptive coping (regardless of adaptive coping), low levels of perceived social support, together with high levels of reported post-traumatic symptoms (re-experiencing, avoidance and arousal, according to the Diagnostic and Statistical Manual of Mental Disorders – Fourth Edition (DSM-IV) criteria) may be considered as markers of a "low resilience" profile of personality, protective factors, risk factors, and outcome among RWs. The opposite pattern may instead be considered as an adaptive profile of resilience. 


## Self-compassion as protective factor



The construct of self-compassion is commonly assessed using the Self-Compassion Scale (SCS) self-report questionnaire. The SCS measures six dimensions of self-compassion, three of which evaluate the active components of self-compassion. These dimensions include Self-kindness (SK), Common humanity (CH), and Mindfulness (MI), which involve being kind and understanding towards oneself, recognizing that personal failures and pain are common experiences, and maintaining awareness of one's painful thoughts and feelings. The remaining three dimensions evaluate the "hindrances" to self-compassion, including Self-judgment (SJ), Isolation (IS), and Overidentification (OI). These dimensions assess factors that hinder self-compassion, such as being self-critical and unsympathetic towards one's shortcomings, isolating oneself from others, and over-identifying with one's painful thoughts and emotions [@neff2022differential].

Compassion fatigue often leads to a sense of helplessness and a feeling of being unable to do more to help others [@boyle2015compassion]. This "learned helplessness" may lead individuals who experience compassion fatigue to rely more on non-self-compassionate coping strategies compared to those who are less affected by compassion fatigue [@gonzalez2021volunteers]. 



decrease the use of self-compassionate responding (i.e., self-kindness, common humanity, mindfulness) and increase uncompassionate responding (i.e., self-judgment, isolation, overidentification) -- see also @gonzalez2021volunteers.



We propose that individuals who experience compassion fatigue may not experience changes in compassionate responding, as their motivation to help others remains intact. However, they may experience a strong increase in uncompassionate responding (e.g., self-blaming), especially in those who are less directly involved in alleviating the suffering of others.


enabling an individual to mobilise internal resources and build up resistance against stressors

individuals with a strong SOC might experience reduced job stress.

-------------------




Sense of coherence (SOC) originates from Antonovsky’s (1979,
1987, 1991, 1993) theory of salutogenesis, a paradigm that focuses
on factors that promote health and well-being and considers the
salutary potential of stressors. SOC is a dispositional orientation that
reflects an individual’s capacity to cope with life stressors and
comprises three components: Comprehensibility, the sense that 
19
stimuli are predictable and structured (cognitive component);
Manageability, the sense that available resources (both internal and
external) are sufficient to cope with demands from the stimuli
(instrumental/behavioural component); and Meaningfulness, the
sense that the demands have significance and are worthy of
investment in terms of personal ideals and standards (motivational
component). An individual’s SOC is reinforced by their “general
resistance resources” (e.g., intelligence, social support, coping
strategies, and preventative health orientation), which are shaped by
life experiences. 

## Instruments

Beside the specific questions for RWs, we administered the following scales to both groups. 

**Self-Compassion Scale.** The Self-Compassion Scale [SCS; @neff2003self; Italian version by @veneziani2017self] is a 26 items  self-report questionnaire, was used to evaluate self-compassion. High levels of self-compassion reflect an ability to be kind and understanding toward oneself, even in difficult times. Three sub-sets of items are considered indicators of compassionate self-responding (CS): SK, CH, and MI. The remaining three sub-sets of items are considered indicators of uncompassionate self-responding (UCS): SJ, IS, and OI. The SCS total score (SCS-TS) is computed by averaging the mean scores of the positive subscales and of the reversely-scored negative subscales. In the present sample, total reliability was $\alpha$ = .89, $\omega$ = .92. Reliability was  adequate for the subscales. SK: $\alpha$ = .84, $\omega$ = .90; CH: $\alpha$ = .72, $\omega$ = .78; MI: $\alpha$ = .75, $\omega$ = .78; SJ: $\alpha$ = .84, $\omega$ = .85; IS: $\alpha$ = .86, $\omega$ = .89; OI: $\alpha$ = .83, $\omega$ = .86. Further psychometric properties of the SCS are presented in the Results section. 

**Post-Traumatic Growth Inventory.** The Post-Traumatic Growth Inventory [PTGI; @tedeschi1996posttraumatic] is a 21 item self-report measure. PTGI evaluates the growth following one or more stressful or traumatic events in one's life. The PTGI comprises five sub-scales (Relating to others, New possibilities, Personal strength, Appreciation of life, and Spiritual change) and has good internal consistency, construct-convergent validity, and discriminant validity [@tedeschi1996posttraumatic]. Also the Italian version has good internal consistency and validity [@prati2014italian]. In the present sample, total reliability was $\alpha$ = .95, $\omega$ = .95. Reliability was adequate for the subscales. Relating to others: $\alpha$ = .91, $\omega$ = .92; New possibilities: $\alpha$ = .86, $\omega$ = .89; Personal strength: $\alpha$ = .82, $\omega$ = .83; Appreciation of life: $\alpha$ = .79, $\omega$ = .81; Spiritual changes: $\alpha$ = .74, $\omega$ = .74.

**Impact of Event Scale - Revised.** The Impact of Event Scale - Revised [IES-R; @weiss2007impact] is a 22-item self-report measure assessing subjective distress caused by traumatic events and it is based on the views of the core phenomena of traumatic-stress reactions: intrusion (B criteria in the DSM-IV PTSD diagnosis), avoidance (C criteria), and persistent hyper-arousal. Correspondingly, the IES-R comprises the sub-scales of Intrusion, Avoidance, and Hyperarousal. The IES-R is widely used to assess the symptomatology of the PTSD in rescue workers. The IES-R show good internal consistency and test–retest stability. The Italian translation show good psychometric properties, good concurrent and discriminant validity, and good test–retest reliability [@craparo2013impact]. In the present sample, total reliability was $\alpha$ = .93, $\omega$ = .94. Reliability was also high for the subscales. Intrusion: $\alpha$ = .90, $\omega$ = .91; Avoidance: $\alpha$ = .78, $\omega$ = .82; Hyperarousal: $\alpha$ = .85, $\omega$ = .87.

**Coping Orientation to Problems Experienced** The Coping Orientation to Problems Experienced test (COPE; @carver1989assessing] is a self-report questionnaire used to evaluate the skills and strategies adopted to face stressful and difficult events. The COPE comprises five dimensions (social support, avoidance strategies, positive attitude, problem-solving, and transcendent orientation) and has adequate internal consistency, and convergent and discriminant validity [@carver1989assessing]. Factor analyses on the Italian version of the COPE [@sica1997coping; @sica2008coping; @sica2021facing] have demonstrated that the scales can be grouped into the following dimensions: Problem-focused, Social Support, Avoidance-oriented, Positive-oriented, and Transcendent-oriented. In the present study, we were interested in the adaptive coping strategies that can be considered on par with self-compassion. Therefore, we only administered the Positive-oriented and Problem-focused subscales. In fact, it is generally acknowledged that positive-oriented coping (e.g., positive reinterpretation and growth, acceptance) is beneficial for managing difficult situations [e.g., @sica2021facing]. Moreover, problem-focused coping is an adaptive and active coping approach (e.g., accepting social support, solving problem, seeking advice or information, and analyzing situation logically) that has been shown to be effective in mediating the development of PTG from self-compassion [@munroe2022using]. In the present sample, total reliability was $\alpha$ = .86, $\omega$ = .87. Reliability was also adequate for the subscales. Positive-oriented: $\alpha$ = .75, $\omega$ = .77; Problem-focused: $\alpha$ = .84, $\omega$ = .85.

**NEO-Five Factor Inventory.** The NEO-Five Factor Inventory (NEO-FFI-60; @costa1992normal) is a 60 items self-report questionnaire, was used to assess five broad domains of personality: Neuroticism (N), Extraversion (E), Openness to experience (O), Agreeableness (A), and Conscientiousness (C). The internal consistency of the five sub-scales of the NEO-FFI-60 is adequate [@murray2003neo]. Items from the Neuroticism and Extraversion domains served as an indicator of latent variables in the structural model; scores for the other three domains were employed for group comparisons in descriptive analyses. In the present sample, we used the Italian version by @caprara2001brand. The Neuroticism ($\alpha$ = .88, $\omega$ = .89), Extraversion ($\alpha$ = .74, $\omega$ = .77) and Conscientiousness ($\alpha$ = .78, $\omega$ = .82) subscales showed adequate internal consistency, whereas reliability was low for the Agreableness ($\alpha$ = .59, $\omega$ = .64) and Openness ($\alpha$ = .59, $\omega$ = .60) subscales.

## Statistical analyses

Latent Profile Analysis (LPA) is a finite mixture modeling technique that partitions individuals into discrete classes based on their responses to observed variables. This technique is particularly useful for identifying subgroups of individuals that can be meaningfully compared [@lanza2013latent]. The primary objectives of LVA are twofold. Firstly, to ensure homogeneity within each identified profile so that individuals grouped together are as similar as possible. Secondly, to maximize heterogeneity between profiles so that each profile accurately represents a distinct grouping of individuals. The classes generated by LVA are considered latent since they are not directly observable but are inferred based on similarities in the data. LPA accounts for measurement errors related to the uncertainty in profile membership and provides fit statistics to determine the number of profiles that best represent the data.

The purpose of the LPA was to detect distinct subgroups of RWs who have different profiles on personality dimensions, protective factors, and outcome variables. Standardized scores for five personality measures (neuroticism, extraversion, openness, agreeableness, conscientiousness), three dimensions of coping (COPE-active coping, COPE-avoidance coping, COPE-social emotional coping), perceived social support (MSPSS), and post-traumatic stress (measured using the IES-R) from the RWs were used as observed indicators for the LPA. 

We fitted a series of LPA models, ranging from 1 to 10 profiles, using 1000 sets of starting values. To determine the optimal number of profiles, we used information criteria, including Bayesian information criterion (BIC), Akaike information criterion (AIC), and adjusted BIC. We selected the model with the lowest value of these criteria, indicating a better fit. Additionally, we evaluated the accuracy of the classification of individuals into the appropriate profile using entropy, with values closer to 1 indicating higher separation among classes (> 0.80 represents high separation). We also employed the Lo-Mendell-Rubin likelihood ratio test (LMR-LRT), a test statistic to compare the fit of a model with a lower versus higher number of profiles. We used MPLUS 8.6 and the `R` software for all statistical analyses.




## Discussion

These results indicate the need for improving pre-employment strategies to select the most resilient individuals for rescue work, to implement continuous preventive measures for personnel. 

## References
